// AUTO-GENERATED from BOOM Provider API + Aria cost_floors + PriceLabs snapshot.
// Regenerate: python3.12 scripts/regenerate-listings-from-boom.py

export type AreaSlug = "regents-park-marylebone" | "old-street-shoreditch" | "kensington-hammersmith" | "fitzrovia-mayfair" | "barbican-farringdon" | "borough-pimlico" | "little-venice-maida-vale";

export type Listing = { slug: string; title: string; area: AreaSlug; areaLabel: string; bedrooms: number; bathrooms: number; maxGuests: number; sizeSqm: number; fromGbpPerNight: number; shortDescription: string; longDescription: string; amenities: string[]; heroImage: string; gallery: string[]; latitude?: number; longitude?: number; postcode?: string; boomListingId?: string; bookingUrl?: string; };

export type Location = { slug: AreaSlug; label: string; shortLabel: string; propertyCountApprox: number; description: string; whyStayHere: string; nearbyHighlights: string[]; transport: string[]; latitude: number; longitude: number; heroImage: string; };

export const LOCATIONS: Location[] = [
  {
    slug: "regents-park-marylebone",
    label: "Regent's Park & Marylebone",
    shortLabel: "Regent's Park & Marylebone",
    propertyCountApprox: 12,
    description: "The heart of Staylio's portfolio. Green parkland, Marylebone village, and St John's Wood townhouses. A quiet, leafy base ten minutes from Oxford Circus.",
    whyStayHere: "Our biggest concentration of apartments. Wide streets, Georgian terraces, the Park at the end of the road. Suits relocations, longer stays, and families wanting calm with central access.",
    nearbyHighlights: ["Regent's Park (5–10 min walk from most apartments)", "Marylebone High Street · Daunt Books, La Fromagerie, the Conran Shop", "Madame Tussauds and Sherlock Holmes Museum", "Lord's Cricket Ground (St John's Wood)", "Wallace Collection (free, ten minutes south)"],
    transport: ["Marylebone (Bakerloo, Chiltern Rail to Birmingham/Oxford)", "Baker Street (Bakerloo, Circle, H&C, Jubilee, Metropolitan)", "St John's Wood (Jubilee)", "Edgware Road (Bakerloo, Circle, District, H&C)"],
    latitude: 51.5234,
    longitude: -0.166,
    heroImage: "https://images.unsplash.com/photo-1543226798-9b00f5b53ddf?w=1600&q=80",
  },
  {
    slug: "old-street-shoreditch",
    label: "Old Street & Shoreditch",
    shortLabel: "Old Street & Shoreditch",
    propertyCountApprox: 14,
    description: "London's creative and tech corridor. Silicon Roundabout, Spitalfields, Brick Lane. Design-led apartments at the seam of finance and east-end street culture.",
    whyStayHere: "Walk to your meeting in the City, then bar-hop through Shoreditch the same evening. Suits founders, designers, consultants on short engagements.",
    nearbyHighlights: ["Spitalfields Market and Old Spitalfields antiques", "Brick Lane (Sunday market, curry mile, vintage)", "Boxpark Shoreditch and Box Hall", "The Curtain rooftop and Shoreditch House (members only)", "Whitechapel Gallery"],
    transport: ["Old Street (Northern)", "Liverpool Street (Central, Circle, Elizabeth, H&C, Metropolitan, National Rail)", "Shoreditch High Street (Overground)", "Hoxton (Overground)"],
    latitude: 51.5253,
    longitude: -0.0801,
    heroImage: "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1600&q=80",
  },
  {
    slug: "kensington-hammersmith",
    label: "Kensington & Hammersmith",
    shortLabel: "Kensington & Hammersmith",
    propertyCountApprox: 6,
    description: "Museums, embassies, leafy garden squares. And across the river, modern Hammersmith with quick Heathrow access. Pairs prestige and practicality.",
    whyStayHere: "Family relocations, museum-week holidays, executive stays close to Imperial College and the Imperial Health Trust. Easy Piccadilly line to Heathrow.",
    nearbyHighlights: ["Natural History Museum, V&A, Science Museum (free)", "Hyde Park and Kensington Gardens", "Holland Park and the Kyoto Garden", "Westfield London (Shepherd's Bush)", "The Design Museum (Holland Park)"],
    transport: ["South Kensington (Circle, District, Piccadilly)", "High Street Kensington (Circle, District)", "Hammersmith (Circle, District, H&C, Piccadilly)", "Direct Piccadilly line to Heathrow"],
    latitude: 51.4988,
    longitude: -0.1749,
    heroImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&q=80",
  },
  {
    slug: "fitzrovia-mayfair",
    label: "Fitzrovia & Mayfair",
    shortLabel: "Fitzrovia & Mayfair",
    propertyCountApprox: 1,
    description: "Charlotte Street restaurants, Mayfair garden squares, Bond Street shopping. London's most prestigious postcodes, walkable to Soho and the West End.",
    whyStayHere: "Executive stays, premium leisure trips, theatre weekends. Five minutes from Oxford Circus and the New Bond Street flagship stores.",
    nearbyHighlights: ["Bond Street and Mount Street shops", "Berkeley Square Gardens", "Charlotte Street restaurant row", "The Wallace Collection (free)", "BFI IMAX and West End theatres"],
    transport: ["Bond Street (Central, Jubilee, Elizabeth)", "Oxford Circus (Bakerloo, Central, Victoria)", "Tottenham Court Road (Central, Northern, Elizabeth)", "Green Park (Jubilee, Piccadilly, Victoria)"],
    latitude: 51.5141,
    longitude: -0.1413,
    heroImage: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1600&q=80",
  },
  {
    slug: "barbican-farringdon",
    label: "Barbican & Farringdon",
    shortLabel: "Barbican & Farringdon",
    propertyCountApprox: 1,
    description: "Brutalist architecture, hidden squares, and the new Elizabeth line. Quiet at weekends, central in the week. The sweet spot of City and culture.",
    whyStayHere: "Walk to the City for finance and tech meetings, walk to Sadler's Wells and the Barbican for arts. Direct Elizabeth line to Heathrow and Canary Wharf.",
    nearbyHighlights: ["The Barbican Centre (concerts, theatre, art-house cinema)", "Sadler's Wells", "Smithfield Market and Charterhouse Square", "St John restaurant and Caravan Exmouth Market", "Museum of London (reopening soon at Smithfield)"],
    transport: ["Barbican (Circle, H&C, Metropolitan)", "Farringdon (Circle, H&C, Metropolitan, Elizabeth, Thameslink)", "Direct Elizabeth line to Heathrow + Canary Wharf", "Direct Thameslink to Gatwick + Luton"],
    latitude: 51.5208,
    longitude: -0.101,
    heroImage: "https://images.unsplash.com/photo-1520637836862-4d197d17c43a?w=1600&q=80",
  },
  {
    slug: "borough-pimlico",
    label: "Borough & Pimlico",
    shortLabel: "Borough & Pimlico",
    propertyCountApprox: 4,
    description: "South Bank food culture and Pimlico's Regency streets. Walk to Tate Modern, the Globe, and Borough Market for breakfast.",
    whyStayHere: "Weekend leisure stays, foodie trips, family-friendly walks along the river. Quieter than the West End, ten minutes from Waterloo.",
    nearbyHighlights: ["Borough Market (one of London's best food markets)", "Tate Modern and the Tate Britain", "The Shard and the Globe", "Westminster, Lambeth Palace, Vauxhall Pleasure Gardens", "Battersea Power Station"],
    transport: ["Borough (Northern)", "London Bridge (Jubilee, Northern, National Rail)", "Pimlico (Victoria)", "Vauxhall (Victoria, National Rail)"],
    latitude: 51.497,
    longitude: -0.1057,
    heroImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1600&q=80",
  },
  {
    slug: "little-venice-maida-vale",
    label: "Little Venice & Maida Vale",
    shortLabel: "Little Venice & Maida Vale",
    propertyCountApprox: 5,
    description: "Canalside cafés, mansion-block flats, the Regent's Canal towpath. London's most underrated residential pocket.",
    whyStayHere: "Longer stays where you want a real neighbourhood feel. Walk along the canal to Camden, or two stops on the Bakerloo to Oxford Circus.",
    nearbyHighlights: ["Little Venice and Regent's Canal towpath", "The Puppet Theatre Barge", "Clifton Nurseries (the oldest garden centre in London)", "Lord's Cricket Ground (next door)", "Walk to Marylebone in 15 minutes"],
    transport: ["Warwick Avenue (Bakerloo)", "Maida Vale (Bakerloo)", "Paddington (Bakerloo, Circle, District, H&C, Elizabeth, Heathrow Express)", "Edgware Road (Bakerloo, Circle, District, H&C)"],
    latitude: 51.5236,
    longitude: -0.1827,
    heroImage: "https://images.unsplash.com/photo-1572297870735-d04ec150e0d2?w=1600&q=80",
  },
];

export const LISTINGS: Listing[] = [
  {
    slug: "borough-pimlico-163-new-kent-rd-e4e562",
    title: "163 New Kent Road · 1-bed",
    area: "borough-pimlico",
    areaLabel: "Borough & Pimlico",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    longDescription: "A 1-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750848039/tenants/NourNest/listings/163NewKentRd-Lukasz-main/pictures/WhatsApp_Image_2025-05-23_at_00.28.18_522c1337_riltic.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750848039/tenants/NourNest/listings/163NewKentRd-Lukasz-main/pictures/WhatsApp_Image_2025-05-23_at_00.28.18_522c1337_riltic.png"],
    latitude: 51.4945478,
    longitude: -0.0923599,
    postcode: "SE1 4AG",
    boomListingId: "e4e56230-34fb-4410-b6e0-de0dd06e51a3",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13535",
  },
  {
    slug: "kensington-hammersmith-shepherds-bush-e90621",
    title: "Shepherd's Bush · 2-bed",
    area: "kensington-hammersmith",
    areaLabel: "Kensington & Hammersmith",
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 6,
    sizeSqm: 0,
    fromGbpPerNight: 165,
    shortDescription: "A 2-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    longDescription: "A 2-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750945056/tenants/NourNest/listings/Shepherd%27sBush-Szymon%280%29-Ops%280%29/pictures/IMG-20250417-WA0166_imqd2o.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750945056/tenants/NourNest/listings/Shepherd%27sBush-Szymon%280%29-Ops%280%29/pictures/IMG-20250417-WA0166_imqd2o.png"],
    latitude: 51.5004716,
    longitude: -0.22142,
    postcode: "W14 0BL",
    boomListingId: "e90621e5-dfca-49e6-9124-773e638bb30c",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/14554",
  },
  {
    slug: "kensington-hammersmith-shepherds-bush-2-e058bd",
    title: "Shepherd's Bush 2 · 2-bed",
    area: "kensington-hammersmith",
    areaLabel: "Kensington & Hammersmith",
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 6,
    sizeSqm: 0,
    fromGbpPerNight: 165,
    shortDescription: "A 2-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    longDescription: "A 2-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1751642069/IMG-20250618-WA0283_op0qv7.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1751642069/IMG-20250618-WA0283_op0qv7.png"],
    latitude: 51.4998617,
    longitude: -0.2249824,
    postcode: "W6 7RN",
    boomListingId: "e058bd2e-92b3-43fd-a06d-a0ef42f80622",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13542",
  },
  {
    slug: "regents-park-marylebone-regents-flat-n-146f40",
    title: "Regent's Flat N · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750851709/tenants/NourNest/listings/RegentsFlatN-Anna%280%29-Ops%288.9%29/pictures/IMG-20250526-WA0107_pnegfj.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750851709/tenants/NourNest/listings/RegentsFlatN-Anna%280%29-Ops%288.9%29/pictures/IMG-20250526-WA0107_pnegfj.png"],
    latitude: 51.5239063,
    longitude: -0.1738172,
    postcode: "NW8 8NQ",
    boomListingId: "146f40ef-a1c0-4035-811a-c2ce40ac853e",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/14451",
  },
  {
    slug: "regents-park-marylebone-euston-1-83a49f",
    title: "Euston Flat 1 · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750856389/WhatsApp_Image_2025-03-21_at_14.40.33_2_dd0y6r.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750856389/WhatsApp_Image_2025-03-21_at_14.40.33_2_dd0y6r.png"],
    latitude: 51.52757500000001,
    longitude: -0.1242196,
    postcode: "WC1H 8BS",
    boomListingId: "83a49f21-c7f3-47ed-a4eb-e627a55f410f",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/15398",
  },
  {
    slug: "kensington-hammersmith-askew-road-f879fa",
    title: "Askew Road · 2-bed",
    area: "kensington-hammersmith",
    areaLabel: "Kensington & Hammersmith",
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 7,
    sizeSqm: 0,
    fromGbpPerNight: 170,
    shortDescription: "A 2-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    longDescription: "A 2-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750437917/tenants/NourNest/listings/AskewRoad-Szymon-main/pictures/IMG-20250618-WA0242_zapa7r.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750437917/tenants/NourNest/listings/AskewRoad-Szymon-main/pictures/IMG-20250618-WA0242_zapa7r.png"],
    latitude: 51.5028829,
    longitude: -0.2432458,
    postcode: "W12 9BL",
    boomListingId: "f879facf-c275-4ac6-b692-132426b35f92",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13517",
  },
  {
    slug: "regents-park-marylebone-regents-flat-m-8f6807",
    title: "Regent's Flat M · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1778840898/ChatGPT_Image_May_14_2026_07_00_25_PM_ky2nij.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1778840898/ChatGPT_Image_May_14_2026_07_00_25_PM_ky2nij.png"],
    latitude: 51.5239063,
    longitude: -0.1738172,
    postcode: "NW8 8NQ",
    boomListingId: "8f6807c2-3847-42a3-af8f-1b71c8db061b",
  },
  {
    slug: "old-street-shoreditch-tower-hill-494cb0",
    title: "Tower Hill · 2-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 6,
    sizeSqm: 0,
    fromGbpPerNight: 255,
    shortDescription: "A 2-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 2-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1776182714/tenants/NourNest/listingsTowerHill-Szymonpictures/WhatsApp_Image_2026-04-09_at_4.42.14_PM_wwslm3.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1776182714/tenants/NourNest/listingsTowerHill-Szymonpictures/WhatsApp_Image_2026-04-09_at_4.42.14_PM_wwslm3.png"],
    latitude: 51.5100942,
    longitude: -0.0683635,
    postcode: "E1 8QW",
    boomListingId: "494cb0cf-9eff-495e-9c03-70dd32d64650",
  },
  {
    slug: "old-street-shoreditch-kings-cross-2a3255",
    title: "King's Cross · 3-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 10,
    sizeSqm: 0,
    fromGbpPerNight: 300,
    shortDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1768938707/IMG-20250827-WA0103_yunll1.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1768938707/IMG-20250827-WA0103_yunll1.png"],
    latitude: 51.5316973,
    longitude: -0.1126701,
    postcode: "N1 9FH",
    boomListingId: "2a32552d-fa34-4389-a5c2-0f9667e970eb",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/15409",
  },
  {
    slug: "little-venice-maida-vale-little-venice-2-1a62a5",
    title: "Little Venice 2 · 3-bed",
    area: "little-venice-maida-vale",
    areaLabel: "Little Venice & Maida Vale",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 9,
    sizeSqm: 0,
    fromGbpPerNight: 215,
    shortDescription: "A 3-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    longDescription: "A 3-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1775228433/ChatGPT_Image_Mar_10_2026_06_15_32_PM_eyu3ui.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1775228433/ChatGPT_Image_Mar_10_2026_06_15_32_PM_eyu3ui.png"],
    latitude: 51.5240797,
    longitude: -0.1772032,
    postcode: "W2 1AT",
    boomListingId: "1a62a553-2ac0-4b47-baf2-3cc0421a00e5",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13532",
  },
  {
    slug: "old-street-shoreditch-hoxton-flat-8-2977ca",
    title: "Hoxton Flat 8 · 3-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 3,
    bathrooms: 1,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 310,
    shortDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1755019277/tenants/NourNest/listings/HoxtonFlat8-Anna-Main/pictures/IMG-20250508-WA0166_zyeo84.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1755019277/tenants/NourNest/listings/HoxtonFlat8-Anna-Main/pictures/IMG-20250508-WA0166_zyeo84.png"],
    latitude: 51.5329629,
    longitude: -0.086474,
    postcode: "N1 5EG",
    boomListingId: "2977ca03-86d5-4146-818b-23aa83087734",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13527",
  },
  {
    slug: "kensington-hammersmith-hammersmith-815a55",
    title: "Hammersmith · 3-bed",
    area: "kensington-hammersmith",
    areaLabel: "Kensington & Hammersmith",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 260,
    shortDescription: "A 3-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    longDescription: "A 3-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750425453/tenants/NourNest/listings/Hammersmith-Szymon-Main/pictures/IMG-20250509-WA0448_tdnp5p.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750425453/tenants/NourNest/listings/Hammersmith-Szymon-Main/pictures/IMG-20250509-WA0448_tdnp5p.png"],
    latitude: 51.4853228,
    longitude: -0.2239988,
    postcode: "W6 9EZ",
    boomListingId: "815a55c6-2b3d-4b37-b88e-1ce3db0208ba",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13525",
  },
  {
    slug: "borough-pimlico-vauxhall-6c8f54",
    title: "Vauxhall · 2-bed",
    area: "borough-pimlico",
    areaLabel: "Borough & Pimlico",
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 6,
    sizeSqm: 0,
    fromGbpPerNight: 225,
    shortDescription: "A 2-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    longDescription: "A 2-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1774556109/IMG-20250521-WA0063_n15vny.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1774556109/IMG-20250521-WA0063_n15vny.png"],
    latitude: 51.4818672,
    longitude: -0.1166707,
    postcode: "SW8 1NJ",
    boomListingId: "6c8f542f-5b1f-402a-88f1-02f7b46b66a5",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13543",
  },
  {
    slug: "fitzrovia-mayfair-mayfair-2bed-449505",
    title: "Mayfair · 2-bed",
    area: "fitzrovia-mayfair",
    areaLabel: "Fitzrovia & Mayfair",
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 7,
    sizeSqm: 0,
    fromGbpPerNight: 195,
    shortDescription: "A 2-bed apartment steps from Bond Street, Mount Street, and the West End.",
    longDescription: "A 2-bed apartment steps from Bond Street, Mount Street, and the West End.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1779388614/tenants/NourNest/listings5BalfourPlace2BDRpictures/R6M28738-HDR_x6rv5c.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1779388614/tenants/NourNest/listings5BalfourPlace2BDRpictures/R6M28738-HDR_x6rv5c.png"],
    latitude: 51.5092565,
    longitude: -0.1522612,
    postcode: "W1K 2AU",
    boomListingId: "449505b5-93ca-4f74-bbdd-01d39f088184",
  },
  {
    slug: "barbican-farringdon-russell-square-flat-34-421231",
    title: "Russell Square Flat 34 · 2-bed",
    area: "barbican-farringdon",
    areaLabel: "Barbican & Farringdon",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 6,
    sizeSqm: 0,
    fromGbpPerNight: 400,
    shortDescription: "A 2-bed apartment on a Georgian square minutes from the Barbican and Farringdon.",
    longDescription: "A 2-bed apartment on a Georgian square minutes from the Barbican and Farringdon.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1766166632/tenants/NourNest/listingsRusselSquareflat34pictures/WhatsApp_Image_2025-12-19_at_1.41.30_PM_1_ils2jz.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1766166632/tenants/NourNest/listingsRusselSquareflat34pictures/WhatsApp_Image_2025-12-19_at_1.41.30_PM_1_ils2jz.png"],
    latitude: 51.5258674,
    longitude: -0.1135651,
    postcode: "WC1X 0FD",
    boomListingId: "421231a5-3ce2-4160-a872-43369d0d4418",
  },
  {
    slug: "little-venice-maida-vale-little-venice-1-ace09d",
    title: "Little Venice 1 · 4-bed",
    area: "little-venice-maida-vale",
    areaLabel: "Little Venice & Maida Vale",
    bedrooms: 4,
    bathrooms: 2,
    maxGuests: 11,
    sizeSqm: 0,
    fromGbpPerNight: 285,
    shortDescription: "A 4-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    longDescription: "A 4-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1752860391/tenants/NourNest/listings/LittleVenice-Szymon-Ops/pictures/IMG-20250410-WA0204_zt0yii.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1752860391/tenants/NourNest/listings/LittleVenice-Szymon-Ops/pictures/IMG-20250410-WA0204_zt0yii.png"],
    latitude: 51.5245147,
    longitude: -0.1779243,
    postcode: "W2 1AT",
    boomListingId: "ace09d7c-b36b-4987-9e67-6d3ab6083a73",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13531",
  },
  {
    slug: "old-street-shoreditch-hackney-1b-bfb561",
    title: "Hackney Flat 1B · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750682205/tenants/NourNest/listings/Hackney1B-Szymon-Main/pictures/IMG-20250421-WA0184_yiho9t.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750682205/tenants/NourNest/listings/Hackney1B-Szymon-Main/pictures/IMG-20250421-WA0184_yiho9t.png"],
    latitude: 51.52763400000001,
    longitude: -0.07689770000000001,
    postcode: "E2 7NX",
    boomListingId: "bfb561ed-c235-4ea5-84f0-5e002a10da28",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13548",
  },
  {
    slug: "old-street-shoreditch-aldgate-1dd5c7",
    title: "Aldgate · 3-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 3,
    bathrooms: 1,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 215,
    shortDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1751628903/tenants/NourNest/listings/Aldgate-Szymon-main/pictures/IMG-20250623-WA0292-2_ozgwju.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1751628903/tenants/NourNest/listings/Aldgate-Szymon-main/pictures/IMG-20250623-WA0292-2_ozgwju.png"],
    latitude: 51.514534,
    longitude: -0.06432159999999999,
    postcode: "E1 1RS",
    boomListingId: "1dd5c7ba-c280-4469-8b1a-6127b1aa6cb8",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13516",
  },
  {
    slug: "regents-park-marylebone-regents-flat-d-a385dd",
    title: "Regent's Flat D · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1760022253/IMG-20250917-WA0022_wsnupj.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1760022253/IMG-20250917-WA0022_wsnupj.png"],
    latitude: 51.5239063,
    longitude: -0.1738172,
    postcode: "NW8 8NQ",
    boomListingId: "a385dd78-f2af-4803-b6dd-066f82537b5f",
  },
  {
    slug: "old-street-shoreditch-old-st-flat-3-1523cb",
    title: "Old Street Flat 3 · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1751291705/tenants/NourNest/listings/OldStFlat3-Szymon-main/pictures/IMG-20250513-WA0055_p8psjl.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1751291705/tenants/NourNest/listings/OldStFlat3-Szymon-main/pictures/IMG-20250513-WA0055_p8psjl.png"],
    latitude: 51.5270111,
    longitude: -0.08012989999999999,
    postcode: "EC1V 9LT",
    boomListingId: "1523cbce-f736-41e4-87d8-77516c606fc4",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13540",
  },
  {
    slug: "borough-pimlico-pimlico-d0fc6e",
    title: "Pimlico · 3-bed",
    area: "borough-pimlico",
    areaLabel: "Borough & Pimlico",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 385,
    shortDescription: "A 3-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    longDescription: "A 3-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1751369291/tenants/NourNest/listings/Pimlico-Blaze-Main%287.8%29/pictures/IMG-20250506-WA0119_fuyvs1.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1751369291/tenants/NourNest/listings/Pimlico-Blaze-Main%287.8%29/pictures/IMG-20250506-WA0119_fuyvs1.png"],
    latitude: 51.4879321,
    longitude: -0.1400843,
    postcode: "SW1V 3EQ",
    boomListingId: "d0fc6e0a-1130-480b-874a-e19c33939ff9",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/14449",
  },
  {
    slug: "old-street-shoreditch-liverpool-rd-4c5f09",
    title: "Liverpool Road · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750776502/tenants/NourNest/listings/LiverpoolRd-Szymon-BDCmain/pictures/IMG-20250512-WA0591_xkzpsj.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750776502/tenants/NourNest/listings/LiverpoolRd-Szymon-BDCmain/pictures/IMG-20250512-WA0591_xkzpsj.png"],
    latitude: 51.5449564,
    longitude: -0.1078811,
    postcode: "N1 1NP",
    boomListingId: "4c5f09e5-6625-48ca-a613-82360732e345",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13533",
  },
  {
    slug: "little-venice-maida-vale-queens-park-c71715",
    title: "Queens Park · 1-bed",
    area: "little-venice-maida-vale",
    areaLabel: "Little Venice & Maida Vale",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 5,
    sizeSqm: 0,
    fromGbpPerNight: 175,
    shortDescription: "A 1-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    longDescription: "A 1-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1774034765/tenants/NourNest/listingsQueensPark-Szymon-Opspictures/ChatGPT_Image_Mar_20_2026_03_49_48_PM_cjkjnl.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1774034765/tenants/NourNest/listingsQueensPark-Szymon-Opspictures/ChatGPT_Image_Mar_20_2026_03_49_48_PM_cjkjnl.png"],
    latitude: 51.53251849999999,
    longitude: -0.2087959,
    postcode: "W10 4BA",
    boomListingId: "c717154e-9328-4e20-9551-edc8ac734924",
  },
  {
    slug: "regents-park-marylebone-regents-flat-e-f9b933",
    title: "Regent's Flat E · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750855245/WhatsApp_Image_2025-04-04_at_14.34.39_elxm9t.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750855245/WhatsApp_Image_2025-04-04_at_14.34.39_elxm9t.png"],
    latitude: 51.5239063,
    longitude: -0.1738172,
    postcode: "NW8 8NQ",
    boomListingId: "f9b933d7-0ca5-45aa-96f7-c96cdd8d3f7f",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/14452",
  },
  {
    slug: "old-street-shoreditch-old-st-flat-1-7a92a4",
    title: "Old Street Flat 1 · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1752858980/tenants/NourNest/listings/OldStFlat1-Szymon-main/pictures/IMG-20250421-WA0151_ftx7ks.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1752858980/tenants/NourNest/listings/OldStFlat1-Szymon-main/pictures/IMG-20250421-WA0151_ftx7ks.png"],
    latitude: 51.5270111,
    longitude: -0.08012989999999999,
    postcode: "EC1V 9LT",
    boomListingId: "7a92a4ad-75ea-4bc7-8f60-89b3de471ab2",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13538",
  },
  {
    slug: "regents-park-marylebone-baker-st-2-94df29",
    title: "Baker Street 2 · 3-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 10,
    sizeSqm: 0,
    fromGbpPerNight: 390,
    shortDescription: "A 3-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 3-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1759764978/tenants/NourNest/listings/BakerSt2-Anna-Ops/pictures/IMG-20250929-WA0213_t0bbal.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1759764978/tenants/NourNest/listings/BakerSt2-Anna-Ops/pictures/IMG-20250929-WA0213_t0bbal.png"],
    latitude: 51.5211023,
    longitude: -0.1584215,
    postcode: "W1U 6BR",
    boomListingId: "94df2945-ac55-4719-b907-f1b933596e6f",
  },
  {
    slug: "old-street-shoreditch-farringdon-2d696f",
    title: "Farringdon · 2-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 265,
    shortDescription: "A 2-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 2-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1738856329/tenants/Londonelite%20property%20management%20ltd/listings/Farringdon-Lukasz-OPS/pictures/_D758182_pgajjv.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1738856329/tenants/Londonelite%20property%20management%20ltd/listings/Farringdon-Lukasz-OPS/pictures/_D758182_pgajjv.png"],
    latitude: 51.5279234,
    longitude: -0.0946062,
    postcode: "EC1V 8DL",
    boomListingId: "2d696f29-cdc9-4718-b553-971a4d0a602d",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13524",
  },
  {
    slug: "kensington-hammersmith-kensington-72a8e2",
    title: "Kensington · 1-bed",
    area: "kensington-hammersmith",
    areaLabel: "Kensington & Hammersmith",
    bedrooms: 1,
    bathrooms: 2,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 165,
    shortDescription: "A 1-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    longDescription: "A 1-bed apartment walking distance to museums, parks, and the Piccadilly line.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750773233/tenants/NourNest/listings/Kensington-Lukasz/pictures/IMG-20250519-WA0290_r44nxd.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750773233/tenants/NourNest/listings/Kensington-Lukasz/pictures/IMG-20250519-WA0290_r44nxd.png"],
    latitude: 51.4956352,
    longitude: -0.2020823,
    postcode: "W14 8PS",
    boomListingId: "72a8e224-db7c-4d95-aa08-b5b373fd9b93",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13530",
  },
  {
    slug: "old-street-shoreditch-63-kings-cross-41cee1",
    title: "King's Cross Flat 63 · 3-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 300,
    shortDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1773948970/tenants/NourNest/listings63King%27sCross-Szymon-Opspictures/WhatsApp_Image_2026-03-19_at_12.07.37_PM_2_a6cmz7.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1773948970/tenants/NourNest/listings63King%27sCross-Szymon-Opspictures/WhatsApp_Image_2026-03-19_at_12.07.37_PM_2_a6cmz7.png"],
    latitude: 51.5375185,
    longitude: -0.1297672,
    postcode: "N1C 4PF",
    boomListingId: "41cee1ca-8b77-4cce-860e-f5876313588e",
  },
  {
    slug: "regents-park-marylebone-regents-flat-3-cf71bf",
    title: "Regent's Flat 3 · 3-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 10,
    sizeSqm: 0,
    fromGbpPerNight: 215,
    shortDescription: "A 3-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 3-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750853677/tenants/NourNest/listings/RegentsFlat3-Anna-ops/pictures/IMG-20250410-WA0036_cmtquu.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750853677/tenants/NourNest/listings/RegentsFlat3-Anna-ops/pictures/IMG-20250410-WA0036_cmtquu.png"],
    latitude: 51.5238112,
    longitude: -0.1740413,
    postcode: "NW8 8NQ",
    boomListingId: "cf71bf9f-da78-49cb-9a4f-9a576abe8a01",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13541",
  },
  {
    slug: "regents-park-marylebone-regents-flat-l-99fa98",
    title: "Regent's Flat L · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750852855/tenants/NourNest/listings/RegentsFlatL-Blaze%285%29-Ops%288.9%29/pictures/IMG-20250526-WA0158_ymmim8.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750852855/tenants/NourNest/listings/RegentsFlatL-Blaze%285%29-Ops%288.9%29/pictures/IMG-20250526-WA0158_ymmim8.png"],
    latitude: 51.5239063,
    longitude: -0.1738172,
    postcode: "NW8 8NQ",
    boomListingId: "99fa98f9-e04f-4b8f-8a53-71af94e3dbde",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/14450",
  },
  {
    slug: "little-venice-maida-vale-atholl-house-b5c1bc",
    title: "Atholl House · 3-bed",
    area: "little-venice-maida-vale",
    areaLabel: "Little Venice & Maida Vale",
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 305,
    shortDescription: "A 3-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    longDescription: "A 3-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750770964/tenants/NourNest/listings/AthollHouse-Anna-main/pictures/IMG-20250425-WA0303_o2mxzp.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750770964/tenants/NourNest/listings/AthollHouse-Anna-main/pictures/IMG-20250425-WA0303_o2mxzp.png"],
    latitude: 51.5287684,
    longitude: -0.182503,
    postcode: "W9 1UR",
    boomListingId: "b5c1bc99-6418-496c-9c8f-0b1feb7429b6",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13518",
  },
  {
    slug: "little-venice-maida-vale-kilburn-4800a9",
    title: "Kilburn · 4-bed",
    area: "little-venice-maida-vale",
    areaLabel: "Little Venice & Maida Vale",
    bedrooms: 4,
    bathrooms: 2,
    maxGuests: 10,
    sizeSqm: 0,
    fromGbpPerNight: 285,
    shortDescription: "A 4-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    longDescription: "A 4-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1752252316/IMG-20250512-WA0643_yysvxp.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1752252316/IMG-20250512-WA0643_yysvxp.png"],
    latitude: 51.5456528082488,
    longitude: -0.1975323325409,
    postcode: "NW6 2JS",
    boomListingId: "4800a991-dbb9-41dd-9088-5a5b219f5c58",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13550",
  },
  {
    slug: "borough-pimlico-london-bridge-3c1664",
    title: "London Bridge · 3-bed",
    area: "borough-pimlico",
    areaLabel: "Borough & Pimlico",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 10,
    sizeSqm: 0,
    fromGbpPerNight: 285,
    shortDescription: "A 3-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    longDescription: "A 3-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1748450512/tenants/NourNest/listings/LondonBridge-Szymon-Ops/pictures/IMG-20250424-WA0197_jwqxfs.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1748450512/tenants/NourNest/listings/LondonBridge-Szymon-Ops/pictures/IMG-20250424-WA0197_jwqxfs.png"],
    latitude: 51.5006729,
    longitude: -0.08509100000000001,
    postcode: "SE1 3FZ",
    boomListingId: "3c166420-d12f-40fb-ab24-827495116c5a",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/15369",
  },
  {
    slug: "regents-park-marylebone-euston-2-56b9e5",
    title: "Euston Flat 2 · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1768486159/IMG-20250519-WA0508_v9rtzs.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1768486159/IMG-20250519-WA0508_v9rtzs.png"],
    latitude: 51.52757500000001,
    longitude: -0.1242196,
    postcode: "WC1H 8BS",
    boomListingId: "56b9e56d-7121-444b-abb3-e6d82e09ebb5",
  },
  {
    slug: "old-street-shoreditch-old-st-flat-2-362ecb",
    title: "Old Street Flat 2 · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1752859070/tenants/NourNest/listings/OldStFlat2-Szymon-main/pictures/IMG-20250428-WA0278_jgk6of.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1752859070/tenants/NourNest/listings/OldStFlat2-Szymon-main/pictures/IMG-20250428-WA0278_jgk6of.png"],
    latitude: 51.527526,
    longitude: -0.0802534,
    postcode: "EC1V 9LT",
    boomListingId: "362ecb60-81a3-41ca-820c-4e24a63e229b",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13539",
  },
  {
    slug: "regents-park-marylebone-regents-flat-w-18e0d6",
    title: "Regent's Flat W · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750854760/IMG-20250616-WA0023_f2q9da.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750854760/IMG-20250616-WA0023_f2q9da.png"],
    latitude: 51.5239063,
    longitude: -0.1738172,
    postcode: "NW8 8NQ",
    boomListingId: "18e0d601-2d25-482e-aaa7-0d915a1876a4",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/14452",
  },
  {
    slug: "regents-park-marylebone-regents-flat-f-e493bc",
    title: "Regent's Flat F · 1-bed",
    area: "regents-park-marylebone",
    areaLabel: "Regent's Park & Marylebone",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 1-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1764872222/tenants/NourNest/listings/RegentsFlatF-Anna-Ops/pictures/IMG-20251203-WA0065_ac8puv.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1764872222/tenants/NourNest/listings/RegentsFlatF-Anna-Ops/pictures/IMG-20251203-WA0065_ac8puv.png"],
    latitude: 51.5239063,
    longitude: -0.1738172,
    postcode: "NW8 8NQ",
    boomListingId: "e493bc05-1c11-4784-95f2-2a9d47eafbbe",
  },
  {
    slug: "old-street-shoreditch-shoreditch-flat-5-a820ac",
    title: "Shoreditch Flat 5 · 4-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 10,
    sizeSqm: 0,
    fromGbpPerNight: 285,
    shortDescription: "A 4-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 4-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1779883229/tenants/NourNest/listingsShoreditchflat5-Szymonpictures/ChatGPT_Image_May_26_2026_06_00_31_PM_u2qt8x.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1779883229/tenants/NourNest/listingsShoreditchflat5-Szymonpictures/ChatGPT_Image_May_26_2026_06_00_31_PM_u2qt8x.png"],
    latitude: 51.52269039999999,
    longitude: -0.0780659,
    postcode: "E1 6PJ",
    boomListingId: "a820acb7-3a1e-4ed7-bd60-30b9d10dbe61",
  },
  {
    slug: "old-street-shoreditch-hoxton-flat-6-3900c6",
    title: "Hoxton Flat 6 · 3-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 3,
    bathrooms: 1,
    maxGuests: 8,
    sizeSqm: 0,
    fromGbpPerNight: 315,
    shortDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 3-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1751365452/tenants/NourNest/listings/HoxtonFlat6-Szymon%280%29-Main%289.3%29/pictures/IMG-20250415-WA0050_gt5z7c.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1751365452/tenants/NourNest/listings/HoxtonFlat6-Szymon%280%29-Main%289.3%29/pictures/IMG-20250415-WA0050_gt5z7c.png"],
    latitude: 51.5329629,
    longitude: -0.086474,
    postcode: "N1 5EG",
    boomListingId: "3900c617-2282-4c59-9a4b-f05629b233ae",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/14447",
  },
  {
    slug: "old-street-shoreditch-old-st-basement-620fc3",
    title: "Old Street Basement · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1753456169/tenants/NourNest/listings/OldStBasement-Lukasz-main/pictures/IMG-20250513-WA0035_el0xl1.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1753456169/tenants/NourNest/listings/OldStBasement-Lukasz-main/pictures/IMG-20250513-WA0035_el0xl1.png"],
    latitude: 51.527526,
    longitude: -0.0802534,
    postcode: "EC1V 9LT",
    boomListingId: "620fc3f0-1a2d-42c0-bfe1-631334a56d02",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13537",
  },
  {
    slug: "little-venice-maida-vale-maida-vale-496fd9",
    title: "Maida Vale · 2-bed",
    area: "little-venice-maida-vale",
    areaLabel: "Little Venice & Maida Vale",
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 6,
    sizeSqm: 0,
    fromGbpPerNight: 260,
    shortDescription: "A 2-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    longDescription: "A 2-bed apartment in a quiet street between Marylebone Village and Regent's Park.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1738003491/tenants/Londonelite%20property%20management%20ltd/listings/MaidaV-Anna%C2%B7Homelike2-bedroomflatinMaidaVale%2CAbbeyRd/pictures/5156aa60-1251-424d-bfb0-de8e4dceed24.jpg",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1738003491/tenants/Londonelite%20property%20management%20ltd/listings/MaidaV-Anna%C2%B7Homelike2-bedroomflatinMaidaVale%2CAbbeyRd/pictures/5156aa60-1251-424d-bfb0-de8e4dceed24.jpg"],
    latitude: 51.5357459,
    longitude: -0.1835459,
    postcode: "NW8 0JN",
    boomListingId: "496fd9b7-df60-450c-b7c2-b73255da9f7f",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13546",
  },
  {
    slug: "little-venice-maida-vale-edgware-rd-cede2d",
    title: "Edgware Road · 4-bed",
    area: "little-venice-maida-vale",
    areaLabel: "Little Venice & Maida Vale",
    bedrooms: 4,
    bathrooms: 2,
    maxGuests: 12,
    sizeSqm: 0,
    fromGbpPerNight: 455,
    shortDescription: "A 4-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    longDescription: "A 4-bed apartment overlooking the Regent's Canal with Bakerloo line at the door.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Smart lock", "Linen + towels", "Fortnightly housekeeping", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1739882990/tenants/NourNest/listings/Edgware-Anna/pictures/IMG-20250217-WA0609_aqub2l.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1739882990/tenants/NourNest/listings/Edgware-Anna/pictures/IMG-20250217-WA0609_aqub2l.png"],
    latitude: 51.5150533,
    longitude: -0.1631986,
    postcode: "W2 2JH",
    boomListingId: "cede2db5-1a4c-4c3f-be7b-e20c4f2dd45f",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/15366",
  },
];

export function listingsByArea(area: AreaSlug): Listing[] { return LISTINGS.filter((l) => l.area === area); }
export function getListing(slug: string): Listing | undefined { return LISTINGS.find((l) => l.slug === slug); }
export function getLocation(slug: AreaSlug): Location | undefined { return LOCATIONS.find((l) => l.slug === slug); }